#!/bin/bash

if [[ -z "$LEMONPATTERNS_HOME" ]]
then
    LEMONPATTERNS_HOME=.
fi

die () {
    echo >&2 "$@"
    exit 1
}

if [ $# -ne 1 ] && [ $# -ne 2 ] 
then
  die "Required argument: lexiconFile" 
fi

if [ ! -d $LEMONPATTERNS_HOME/lib ]
then
  mkdir lib
fi

if [ ! -e $LEMONPATTERNS_HOME/lib/scala-library-2.11.11.jar ]
then
  echo "Obtaining Scala library"
  wget http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar -O lib/scala-library-2.11.11.jar || die "wget failed"
fi

if [ ! -e $LEMONPATTERNS_HOME/lib/scala-xml_2.11-1.0.6.jar ]
then
  echo "Obtaining Scala library"
  wget http://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.6/scala-xml_2.11-1.0.6.jar -O lib/scala-xml_2.11-1.0.6.jar
fi


if [ ! -e $LEMONPATTERNS_HOME/lib/jflex-1.4.3.jar ]
then
  echo "Obtaining JFlex"
  wget http://repo1.maven.org/maven2/de/jflex/jflex/1.4.3/jflex-1.4.3.jar -O lib/jflex-1.4.3.jar || die "wget failed"
fi

if [ ! -e $LEMONPATTERNS_HOME/target/lemon.patterns_2.11.11-1.17.6.jar ]
then
  echo "Compiling sources"
  mvn install || die "Maven failed"
fi

java -cp $LEMONPATTERNS_HOME/lib/scala-xml_2.11-1.0.6.jar:$LEMONPATTERNS_HOME/lib/scala-library-2.11.11.jar:$LEMONPATTERNS_HOME/lib/jflex-1.4.3.jar:$LEMONPATTERNS_HOME/target/lemon.patterns_2.11.11-1.17.6.jar net.lemonmodel.patterns.ConvertPatterns "$@"

