#!/bin/bash

die () {
    echo >&2 "$@"
    exit 1
}

if [ $# -ne 1 ] && [ $# -ne 2 ] 
then
  die "Required argument: lexiconFile" 
fi

if [ ! -d lib ]
then
	die "Directory lib does not exist!"
fi

if [ ! -e lib/scala-library-2.9.1.jar ]
then
  echo "Obtaining Scala library"
  wget http://repo1.maven.org/maven2/org/scala-lang/scala-library/2.9.1/scala-library-2.9.1.jar -O lib/scala-library-2.9.1.jar || die "wget failed"
fi

if [ ! -e lib/jflex-1.4.3.jar ]
then
  echo "Obtaining JFlex"
  wget http://repo1.maven.org/maven2/de/jflex/jflex/1.4.3/jflex-1.4.3.jar -O lib/jflex-1.4.3.jar || die "wget failed"
fi

if [ ! -e target/lemon.patterns_2.9.1-1.12.9.jar ]
then
  echo "Compiling sources"
  mvn install || die "Maven failed"
fi

java -cp lib/scala-library-2.9.1.jar:lib/jflex-1.4.3.jar:target/lemon.patterns_2.9.1-1.12.9.jar net.lemonmodel.patterns.ConvertPatterns "$@"

