package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class AP implements java.io.Serializable {
  public abstract <R,A> R accept(AP.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAPSimple p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAPComplex p, A arg);

  }

}
