package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Arg implements java.io.Serializable {
  public abstract <R,A> R accept(Arg.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESubject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EDirectObject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EIndirectObject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ECopulativeArg p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ECopulativeSubject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPrepositionalObject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPostpositionalObject p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPossessiveAdjunct p, A arg);

  }

}
