package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class BoundedScalarMembership extends ScalarMembership {
  public final Double double_1, double_2;
  public final URI uri_1, uri_2;

  public BoundedScalarMembership(Double p1, URI p2, Double p3, URI p4) { double_1 = p1; uri_1 = p2; double_2 = p3; uri_2 = p4; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.ScalarMembership.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.BoundedScalarMembership) {
      net.lemonmodel.patterns.parser.Absyn.BoundedScalarMembership x = (net.lemonmodel.patterns.parser.Absyn.BoundedScalarMembership)o;
      return this.double_1.equals(x.double_1) && this.uri_1.equals(x.uri_1) && this.double_2.equals(x.double_2) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.double_1.hashCode())+this.uri_1.hashCode())+this.double_2.hashCode())+this.uri_2.hashCode();
  }


}
