package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Category implements java.io.Serializable {
  public abstract <R,A> R accept(Category.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESingular p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EDual p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPlural p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAbessive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAblative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAbsolutive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAccusative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAdessive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAditive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAllative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EBenefactive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ECausative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EComitative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EDative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EDelative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EElative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EEquative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EErgative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EEssive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EGenitive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EIllative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EInessive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EInstrumental p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ELative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ELocative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ENominative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EOblique p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPartitive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EProlative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESociative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESublative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESuperessive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ETerminative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ETranslative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EVocative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EComparative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESuperlative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPresent p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPast p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EFuture p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EFirstPerson p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESecondPerson p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EThirdPerson p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EImperfect p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EImperative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EIndicative p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ESubjunctive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EConditional p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EGerundive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EInfinitive p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EParticiple p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EAnyCat p, A arg);

  }

}
