package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EAdjective extends Pattern {
  public final AdjectivePattern adjectivepattern_;

  public EAdjective(AdjectivePattern p1) { adjectivepattern_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EAdjective) {
      net.lemonmodel.patterns.parser.Absyn.EAdjective x = (net.lemonmodel.patterns.parser.Absyn.EAdjective)o;
      return this.adjectivepattern_.equals(x.adjectivepattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.adjectivepattern_.hashCode();
  }


}
