package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EAnyCat extends Category {
  public final URI uri_1, uri_2;

  public EAnyCat(URI p1, URI p2) { uri_1 = p1; uri_2 = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Category.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EAnyCat) {
      net.lemonmodel.patterns.parser.Absyn.EAnyCat x = (net.lemonmodel.patterns.parser.Absyn.EAnyCat)o;
      return this.uri_1.equals(x.uri_1) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uri_1.hashCode())+this.uri_2.hashCode();
  }


}
