package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EArgAsOFE extends OntologyFrameElement {
  public final Arg arg_;

  public EArgAsOFE(Arg p1) { arg_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.OntologyFrameElement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EArgAsOFE) {
      net.lemonmodel.patterns.parser.Absyn.EArgAsOFE x = (net.lemonmodel.patterns.parser.Absyn.EArgAsOFE)o;
      return this.arg_.equals(x.arg_);
    }
    return false;
  }

  public int hashCode() {
    return this.arg_.hashCode();
  }


}
