package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EClassNoun extends NounPattern {
  public final NP np_;
  public final URI uri_;

  public EClassNoun(NP p1, URI p2) { np_ = p1; uri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.NounPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EClassNoun) {
      net.lemonmodel.patterns.parser.Absyn.EClassNoun x = (net.lemonmodel.patterns.parser.Absyn.EClassNoun)o;
      return this.np_.equals(x.np_) && this.uri_.equals(x.uri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.np_.hashCode())+this.uri_.hashCode();
  }


}
