package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EClassRelationalNoun1 extends NounPattern {
  public final NP np_;
  public final URI uri_1, uri_2;
  public final Arg arg_1, arg_2;

  public EClassRelationalNoun1(NP p1, URI p2, URI p3, Arg p4, Arg p5) { np_ = p1; uri_1 = p2; uri_2 = p3; arg_1 = p4; arg_2 = p5; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.NounPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EClassRelationalNoun1) {
      net.lemonmodel.patterns.parser.Absyn.EClassRelationalNoun1 x = (net.lemonmodel.patterns.parser.Absyn.EClassRelationalNoun1)o;
      return this.np_.equals(x.np_) && this.uri_1.equals(x.uri_1) && this.uri_2.equals(x.uri_2) && this.arg_1.equals(x.arg_1) && this.arg_2.equals(x.arg_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.np_.hashCode())+this.uri_1.hashCode())+this.uri_2.hashCode())+this.arg_1.hashCode())+this.arg_2.hashCode();
  }


}
