package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EConsequenceVerb7 extends VerbPattern {
  public final VP vp_;
  public final URI uri_1, uri_2;

  public EConsequenceVerb7(VP p1, URI p2, URI p3) { vp_ = p1; uri_1 = p2; uri_2 = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.VerbPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb7) {
      net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb7 x = (net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb7)o;
      return this.vp_.equals(x.vp_) && this.uri_1.equals(x.uri_1) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.vp_.hashCode())+this.uri_1.hashCode())+this.uri_2.hashCode();
  }


}
