package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EConsequenceVerb5 extends VerbPattern {
  public final VP vp_;
  public final URI uri_1, uri_2;
  public final OntologyFrameElement ontologyframeelement_;

  public EConsequenceVerb5(VP p1, URI p2, OntologyFrameElement p3, URI p4) { vp_ = p1; uri_1 = p2; ontologyframeelement_ = p3; uri_2 = p4; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.VerbPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb5) {
      net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb5 x = (net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb5)o;
      return this.vp_.equals(x.vp_) && this.uri_1.equals(x.uri_1) && this.ontologyframeelement_.equals(x.ontologyframeelement_) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.vp_.hashCode())+this.uri_1.hashCode())+this.ontologyframeelement_.hashCode())+this.uri_2.hashCode();
  }


}
