package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EConsequenceVerb1 extends VerbPattern {
  public final VP vp_;
  public final URI uri_1, uri_2;
  public final Arg arg_1, arg_2;

  public EConsequenceVerb1(VP p1, URI p2, Arg p3, Arg p4, URI p5) { vp_ = p1; uri_1 = p2; arg_1 = p3; arg_2 = p4; uri_2 = p5; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.VerbPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb1) {
      net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb1 x = (net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb1)o;
      return this.vp_.equals(x.vp_) && this.uri_1.equals(x.uri_1) && this.arg_1.equals(x.arg_1) && this.arg_2.equals(x.arg_2) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.vp_.hashCode())+this.uri_1.hashCode())+this.arg_1.hashCode())+this.arg_2.hashCode())+this.uri_2.hashCode();
  }


}
