package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EConsequenceVerb2 extends VerbPattern {
  public final VP vp_;
  public final URI uri_;
  public final OntologyFrameElement ontologyframeelement_1, ontologyframeelement_2;

  public EConsequenceVerb2(VP p1, URI p2, OntologyFrameElement p3, OntologyFrameElement p4) { vp_ = p1; uri_ = p2; ontologyframeelement_1 = p3; ontologyframeelement_2 = p4; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.VerbPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb2) {
      net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb2 x = (net.lemonmodel.patterns.parser.Absyn.EConsequenceVerb2)o;
      return this.vp_.equals(x.vp_) && this.uri_.equals(x.uri_) && this.ontologyframeelement_1.equals(x.ontologyframeelement_1) && this.ontologyframeelement_2.equals(x.ontologyframeelement_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.vp_.hashCode())+this.uri_.hashCode())+this.ontologyframeelement_1.hashCode())+this.ontologyframeelement_2.hashCode();
  }


}
