package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ECorePattern extends PatternType {
  public final Pattern pattern_;

  public ECorePattern(Pattern p1) { pattern_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.PatternType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ECorePattern) {
      net.lemonmodel.patterns.parser.Absyn.ECorePattern x = (net.lemonmodel.patterns.parser.Absyn.ECorePattern)o;
      return this.pattern_.equals(x.pattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.pattern_.hashCode();
  }


}
