package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EIntersectiveObjectPropertyAdjective extends AdjectivePattern {
  public final AP ap_;
  public final URI uri_1, uri_2;

  public EIntersectiveObjectPropertyAdjective(AP p1, URI p2, URI p3) { ap_ = p1; uri_1 = p2; uri_2 = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.AdjectivePattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EIntersectiveObjectPropertyAdjective) {
      net.lemonmodel.patterns.parser.Absyn.EIntersectiveObjectPropertyAdjective x = (net.lemonmodel.patterns.parser.Absyn.EIntersectiveObjectPropertyAdjective)o;
      return this.ap_.equals(x.ap_) && this.uri_1.equals(x.uri_1) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ap_.hashCode())+this.uri_1.hashCode())+this.uri_2.hashCode();
  }


}
