package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EIntersectiveDataPropertyAdjective extends AdjectivePattern {
  public final AP ap_;
  public final URI uri_;
  public final String string_;

  public EIntersectiveDataPropertyAdjective(AP p1, URI p2, String p3) { ap_ = p1; uri_ = p2; string_ = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.AdjectivePattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EIntersectiveDataPropertyAdjective) {
      net.lemonmodel.patterns.parser.Absyn.EIntersectiveDataPropertyAdjective x = (net.lemonmodel.patterns.parser.Absyn.EIntersectiveDataPropertyAdjective)o;
      return this.ap_.equals(x.ap_) && this.uri_.equals(x.uri_) && this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ap_.hashCode())+this.uri_.hashCode())+this.string_.hashCode();
  }


}
