package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EIntersectiveAdjective extends AdjectivePattern {
  public final AP ap_;
  public final URI uri_;

  public EIntersectiveAdjective(AP p1, URI p2) { ap_ = p1; uri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.AdjectivePattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EIntersectiveAdjective) {
      net.lemonmodel.patterns.parser.Absyn.EIntersectiveAdjective x = (net.lemonmodel.patterns.parser.Absyn.EIntersectiveAdjective)o;
      return this.ap_.equals(x.ap_) && this.uri_.equals(x.uri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ap_.hashCode())+this.uri_.hashCode();
  }


}
