package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ELemmaPOSTaggedHeadWord extends POSTaggedWord {
  public final String string_1, string_2;
  public final POSTag postag_;

  public ELemmaPOSTaggedHeadWord(String p1, String p2, POSTag p3) { string_1 = p1; string_2 = p2; postag_ = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.POSTaggedWord.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ELemmaPOSTaggedHeadWord) {
      net.lemonmodel.patterns.parser.Absyn.ELemmaPOSTaggedHeadWord x = (net.lemonmodel.patterns.parser.Absyn.ELemmaPOSTaggedHeadWord)o;
      return this.string_1.equals(x.string_1) && this.string_2.equals(x.string_2) && this.postag_.equals(x.postag_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.string_1.hashCode())+this.string_2.hashCode())+this.postag_.hashCode();
  }


}
