package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EName extends NounPattern {
  public final PNP pnp_;
  public final URI uri_;

  public EName(PNP p1, URI p2) { pnp_ = p1; uri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.NounPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EName) {
      net.lemonmodel.patterns.parser.Absyn.EName x = (net.lemonmodel.patterns.parser.Absyn.EName)o;
      return this.pnp_.equals(x.pnp_) && this.uri_.equals(x.uri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pnp_.hashCode())+this.uri_.hashCode();
  }


}
