package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ENounWithGender extends Pattern {
  public final NounPattern nounpattern_;
  public final Gender gender_;

  public ENounWithGender(NounPattern p1, Gender p2) { nounpattern_ = p1; gender_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ENounWithGender) {
      net.lemonmodel.patterns.parser.Absyn.ENounWithGender x = (net.lemonmodel.patterns.parser.Absyn.ENounWithGender)o;
      return this.nounpattern_.equals(x.nounpattern_) && this.gender_.equals(x.gender_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.nounpattern_.hashCode())+this.gender_.hashCode();
  }


}
