package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ENoun extends Pattern {
  public final NounPattern nounpattern_;

  public ENoun(NounPattern p1) { nounpattern_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ENoun) {
      net.lemonmodel.patterns.parser.Absyn.ENoun x = (net.lemonmodel.patterns.parser.Absyn.ENoun)o;
      return this.nounpattern_.equals(x.nounpattern_);
    }
    return false;
  }

  public int hashCode() {
    return this.nounpattern_.hashCode();
  }


}
