package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EOptionalArg extends Arg {
  public final Arg arg_;

  public EOptionalArg(Arg p1) { arg_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EOptionalArg) {
      net.lemonmodel.patterns.parser.Absyn.EOptionalArg x = (net.lemonmodel.patterns.parser.Absyn.EOptionalArg)o;
      return this.arg_.equals(x.arg_);
    }
    return false;
  }

  public int hashCode() {
    return this.arg_.hashCode();
  }


}
