package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EPrefix extends Statement {
  public final String ident_, fulluri_;

  public EPrefix(String p1, String p2) { ident_ = p1; fulluri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Statement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EPrefix) {
      net.lemonmodel.patterns.parser.Absyn.EPrefix x = (net.lemonmodel.patterns.parser.Absyn.EPrefix)o;
      return this.ident_.equals(x.ident_) && this.fulluri_.equals(x.fulluri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.fulluri_.hashCode();
  }


}
