package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EQName2 extends URI {
  public final String ident_;

  public EQName2(String p1) { ident_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.URI.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EQName2) {
      net.lemonmodel.patterns.parser.Absyn.EQName2 x = (net.lemonmodel.patterns.parser.Absyn.EQName2)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
