package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ERelationalMultivalentNoun extends NounPattern {
  public final NP np_;
  public final URI uri_;
  public final ListOntologyFrameElement listontologyframeelement_;

  public ERelationalMultivalentNoun(NP p1, URI p2, ListOntologyFrameElement p3) { np_ = p1; uri_ = p2; listontologyframeelement_ = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.NounPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ERelationalMultivalentNoun) {
      net.lemonmodel.patterns.parser.Absyn.ERelationalMultivalentNoun x = (net.lemonmodel.patterns.parser.Absyn.ERelationalMultivalentNoun)o;
      return this.np_.equals(x.np_) && this.uri_.equals(x.uri_) && this.listontologyframeelement_.equals(x.listontologyframeelement_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.np_.hashCode())+this.uri_.hashCode())+this.listontologyframeelement_.hashCode();
  }


}
