package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ERelationalNoun2 extends NounPattern {
  public final NP np_;
  public final URI uri_;
  public final Arg arg_;

  public ERelationalNoun2(NP p1, URI p2, Arg p3) { np_ = p1; uri_ = p2; arg_ = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.NounPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ERelationalNoun2) {
      net.lemonmodel.patterns.parser.Absyn.ERelationalNoun2 x = (net.lemonmodel.patterns.parser.Absyn.ERelationalNoun2)o;
      return this.np_.equals(x.np_) && this.uri_.equals(x.uri_) && this.arg_.equals(x.arg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.np_.hashCode())+this.uri_.hashCode())+this.arg_.hashCode();
  }


}
