package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class ERestrictedArg extends Arg {
  public final Arg arg_;
  public final URI uri_;

  public ERestrictedArg(Arg p1, URI p2) { arg_ = p1; uri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.ERestrictedArg) {
      net.lemonmodel.patterns.parser.Absyn.ERestrictedArg x = (net.lemonmodel.patterns.parser.Absyn.ERestrictedArg)o;
      return this.arg_.equals(x.arg_) && this.uri_.equals(x.uri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.arg_.hashCode())+this.uri_.hashCode();
  }


}
