package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EStatments extends Statements {
  public final ListStatement liststatement_;

  public EStatments(ListStatement p1) { liststatement_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.Statements.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EStatments) {
      net.lemonmodel.patterns.parser.Absyn.EStatments x = (net.lemonmodel.patterns.parser.Absyn.EStatments)o;
      return this.liststatement_.equals(x.liststatement_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststatement_.hashCode();
  }


}
