package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EStateVerb1 extends VerbPattern {
  public final VP vp_;
  public final URI uri_;

  public EStateVerb1(VP p1, URI p2) { vp_ = p1; uri_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.VerbPattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EStateVerb1) {
      net.lemonmodel.patterns.parser.Absyn.EStateVerb1 x = (net.lemonmodel.patterns.parser.Absyn.EStateVerb1)o;
      return this.vp_.equals(x.vp_) && this.uri_.equals(x.uri_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.vp_.hashCode())+this.uri_.hashCode();
  }


}
