package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EURIAsSynArg extends OntologyFrameElement {
  public final URI uri_;
  public final Arg arg_;

  public EURIAsSynArg(URI p1, Arg p2) { uri_ = p1; arg_ = p2; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.OntologyFrameElement.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EURIAsSynArg) {
      net.lemonmodel.patterns.parser.Absyn.EURIAsSynArg x = (net.lemonmodel.patterns.parser.Absyn.EURIAsSynArg)o;
      return this.uri_.equals(x.uri_) && this.arg_.equals(x.arg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uri_.hashCode())+this.arg_.hashCode();
  }


}
