package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class EURI extends URI {
  public final String fulluri_;

  public EURI(String p1) { fulluri_ = p1; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.URI.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.EURI) {
      net.lemonmodel.patterns.parser.Absyn.EURI x = (net.lemonmodel.patterns.parser.Absyn.EURI)o;
      return this.fulluri_.equals(x.fulluri_);
    }
    return false;
  }

  public int hashCode() {
    return this.fulluri_.hashCode();
  }


}
