package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public class LessThanScalarMembership extends ScalarMembership {
  public final URI uri_1, uri_2;
  public final Double double_;

  public LessThanScalarMembership(URI p1, Double p2, URI p3) { uri_1 = p1; double_ = p2; uri_2 = p3; }

  public <R,A> R accept(net.lemonmodel.patterns.parser.Absyn.ScalarMembership.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof net.lemonmodel.patterns.parser.Absyn.LessThanScalarMembership) {
      net.lemonmodel.patterns.parser.Absyn.LessThanScalarMembership x = (net.lemonmodel.patterns.parser.Absyn.LessThanScalarMembership)o;
      return this.uri_1.equals(x.uri_1) && this.double_.equals(x.double_) && this.uri_2.equals(x.uri_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.uri_1.hashCode())+this.double_.hashCode())+this.uri_2.hashCode();
  }


}
