package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class PNP implements java.io.Serializable {
  public abstract <R,A> R accept(PNP.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPNPSimple p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.EPNPComplex p, A arg);

  }

}
