package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class ScalarMembership implements java.io.Serializable {
  public abstract <R,A> R accept(ScalarMembership.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.CovariantScalarMembership p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.ContravariantScalarMembership p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.GreaterThanScalarMembership p, A arg);
    public R visit(net.lemonmodel.patterns.parser.Absyn.LessThanScalarMembership p, A arg);

  }

}
