package net.lemonmodel.patterns.parser.Absyn; // Java Package generated by the BNF Converter.

public abstract class Statements implements java.io.Serializable {
  public abstract <R,A> R accept(Statements.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(net.lemonmodel.patterns.parser.Absyn.EStatments p, A arg);

  }

}
