
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Apr 08 13:08:32 CEST 2014
//----------------------------------------------------

package net.lemonmodel.patterns.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int _SYMB_39 = 41;
  public static final int _SYMB_38 = 40;
  public static final int _SYMB_37 = 39;
  public static final int _SYMB_36 = 38;
  public static final int _SYMB_35 = 37;
  public static final int _SYMB_99 = 101;
  public static final int _SYMB_34 = 36;
  public static final int _SYMB_98 = 100;
  public static final int _SYMB_33 = 35;
  public static final int _SYMB_97 = 99;
  public static final int _SYMB_32 = 34;
  public static final int _SYMB_96 = 98;
  public static final int _SYMB_31 = 33;
  public static final int _SYMB_95 = 97;
  public static final int _SYMB_30 = 32;
  public static final int _DOUBLE_ = 108;
  public static final int _SYMB_94 = 96;
  public static final int _SYMB_93 = 95;
  public static final int _SYMB_92 = 94;
  public static final int _SYMB_91 = 93;
  public static final int _SYMB_90 = 92;
  public static final int _SYMB_29 = 31;
  public static final int _SYMB_28 = 30;
  public static final int _SYMB_27 = 29;
  public static final int _SYMB_26 = 28;
  public static final int _SYMB_25 = 27;
  public static final int _SYMB_89 = 91;
  public static final int _SYMB_24 = 26;
  public static final int _SYMB_88 = 90;
  public static final int _SYMB_23 = 25;
  public static final int _SYMB_87 = 89;
  public static final int _SYMB_22 = 24;
  public static final int _SYMB_86 = 88;
  public static final int _SYMB_21 = 23;
  public static final int _SYMB_85 = 87;
  public static final int _SYMB_20 = 22;
  public static final int _SYMB_84 = 86;
  public static final int _SYMB_83 = 85;
  public static final int _SYMB_82 = 84;
  public static final int _SYMB_81 = 83;
  public static final int _SYMB_80 = 82;
  public static final int _SYMB_19 = 21;
  public static final int _SYMB_18 = 20;
  public static final int _SYMB_17 = 19;
  public static final int _SYMB_16 = 18;
  public static final int _SYMB_15 = 17;
  public static final int _SYMB_79 = 81;
  public static final int _SYMB_14 = 16;
  public static final int _SYMB_78 = 80;
  public static final int _SYMB_9 = 11;
  public static final int _SYMB_13 = 15;
  public static final int _SYMB_77 = 79;
  public static final int _SYMB_8 = 10;
  public static final int _SYMB_12 = 14;
  public static final int _SYMB_76 = 78;
  public static final int _SYMB_7 = 9;
  public static final int _SYMB_11 = 13;
  public static final int _SYMB_75 = 77;
  public static final int _SYMB_6 = 8;
  public static final int _SYMB_10 = 12;
  public static final int _SYMB_74 = 76;
  public static final int _SYMB_5 = 7;
  public static final int _SYMB_73 = 75;
  public static final int _SYMB_4 = 6;
  public static final int _SYMB_72 = 74;
  public static final int _SYMB_3 = 5;
  public static final int _SYMB_71 = 73;
  public static final int _SYMB_2 = 4;
  public static final int _SYMB_70 = 72;
  public static final int _SYMB_1 = 3;
  public static final int _SYMB_0 = 2;
  public static final int _SYMB_69 = 71;
  public static final int _SYMB_68 = 70;
  public static final int _SYMB_67 = 69;
  public static final int _SYMB_66 = 68;
  public static final int _SYMB_65 = 67;
  public static final int _SYMB_64 = 66;
  public static final int _STRING_ = 107;
  public static final int _SYMB_63 = 65;
  public static final int _SYMB_62 = 64;
  public static final int EOF = 0;
  public static final int _SYMB_61 = 63;
  public static final int _SYMB_60 = 62;
  public static final int error = 1;
  public static final int _SYMB_59 = 61;
  public static final int _SYMB_58 = 60;
  public static final int _SYMB_57 = 59;
  public static final int _SYMB_56 = 58;
  public static final int _SYMB_55 = 57;
  public static final int _SYMB_54 = 56;
  public static final int _SYMB_53 = 55;
  public static final int _SYMB_52 = 54;
  public static final int _SYMB_51 = 53;
  public static final int _SYMB_50 = 52;
  public static final int _SYMB_104 = 106;
  public static final int _SYMB_103 = 105;
  public static final int _IDENT_ = 109;
  public static final int _SYMB_102 = 104;
  public static final int _SYMB_101 = 103;
  public static final int _SYMB_100 = 102;
  public static final int FullURI = 110;
  public static final int _SYMB_49 = 51;
  public static final int _SYMB_48 = 50;
  public static final int _SYMB_47 = 49;
  public static final int _SYMB_46 = 48;
  public static final int _SYMB_45 = 47;
  public static final int _SYMB_44 = 46;
  public static final int _SYMB_43 = 45;
  public static final int _SYMB_42 = 44;
  public static final int _SYMB_41 = 43;
  public static final int _SYMB_40 = 42;
}

